Trigger Release

diff --git a/.github/workflows/pr_preview.yml b/.github/workflows/pr_preview.yml
--- a/.github/workflows/pr_preview.yml
+++ b/.github/workflows/pr_preview.yml
@@ -1,159 +1,159 @@
-name: Build test link and Deploy to Cloudflare Pages
+# name: Build test link and Deploy to Cloudflare Pages
 
-permissions:
-    actions: write # Necessary to cancel workflow executions
-    checks: write # Necessary to write reports
-    pull-requests: write # Necessary to comment on PRs
-    contents: read
+# permissions:
+#     actions: write # Necessary to cancel workflow executions
+#     checks: write # Necessary to write reports
+#     pull-requests: write # Necessary to comment on PRs
+#     contents: read
 
-on:
-    pull_request_target:
-        types: [opened, synchronize]
-        branches:
-            - '**'
+# on:
+#     pull_request_target:
+#         types: [opened, synchronize]
+#         branches:
+#             - '**'
 
-concurrency:
-    group: cloudflare-pages-build-${{github.head_ref}}
-    cancel-in-progress: true
+# concurrency:
+#     group: cloudflare-pages-build-${{github.head_ref}}
+#     cancel-in-progress: true
 
-jobs:
-    build_to_cloudflare_pages:
-        timeout-minutes: 30
-        runs-on: ubuntu-latest
-        environment: staging
-        steps:
-            - name: Checkout to branch
-              uses: actions/checkout@v4
-              with:
-                  ref: ${{ github.event.pull_request.head.sha }}
+# jobs:
+#     build_to_cloudflare_pages:
+#         timeout-minutes: 30
+#         runs-on: ubuntu-latest
+#         environment: staging
+#         steps:
+#             - name: Checkout to branch
+#               uses: actions/checkout@v4
+#               with:
+#                   ref: ${{ github.event.pull_request.head.sha }}
 
-            - name: Setup Node
-              uses: "./.github/actions/setup_node"
+#             - name: Setup Node
+#               uses: "./.github/actions/setup_node"
 
-            - name: 'Generate action link comment'
-              id: generate_action_url
-              uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
-              with:
-                  github-token: ${{ github.token }}
-                  script: |
-                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
-                      const comment = [
-                          '| Name | Result |',
-                          '| :--- | :------ |',
-                          `| **Build status**  | Building 🔨 |`,
-                          `| **Action URL**  | [Visit Action](${action_url}) |`,
-                          ''
-                        ].join('\n')
-                      core.setOutput("comment", comment);
+#             - name: 'Generate action link comment'
+#               id: generate_action_url
+#               uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
+#               with:
+#                   github-token: ${{ github.token }}
+#                   script: |
+#                       const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
+#                       const comment = [
+#                           '| Name | Result |',
+#                           '| :--- | :------ |',
+#                           `| **Build status**  | Building 🔨 |`,
+#                           `| **Action URL**  | [Visit Action](${action_url}) |`,
+#                           ''
+#                         ].join('\n')
+#                       core.setOutput("comment", comment);
 
-            - name: Post Cloudflare Pages Preview comment
-              uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd
-              with:
-                  header: Cloudflare Pages Preview Comment
-                  number: ${{github.event.number}}
-                  message: ${{steps.generate_action_url.outputs.comment}}
-                  recreate: true
+#             - name: Post Cloudflare Pages Preview comment
+#               uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd
+#               with:
+#                   header: Cloudflare Pages Preview Comment
+#                   number: ${{github.event.number}}
+#                   message: ${{steps.generate_action_url.outputs.comment}}
+#                   recreate: true
 
-            - name: Install Dependencies
-              uses: "./.github/actions/npm_install_from_cache"
+#             - name: Install Dependencies
+#               uses: "./.github/actions/npm_install_from_cache"
 
-            - name: Build staging
-              run: npm run build:all
-              env:
-                  NODE_ENV: staging
-                  RUDDERSTACK_KEY: ${{ secrets.RUDDERSTACK_KEY }}
-                  REF_NAME: ${{ github.head_ref }}
-                  R2_PROJECT_NAME: ${{ vars.R2_PROJECT_NAME }}
-                  CROWDIN_BRANCH_NAME: ${{ vars.CROWDIN_BRANCH_NAME }}
-                  REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
-                  TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
+#             - name: Build staging
+#               run: npm run build:all
+#               env:
+#                   NODE_ENV: staging
+#                   RUDDERSTACK_KEY: ${{ secrets.RUDDERSTACK_KEY }}
+#                   REF_NAME: ${{ github.head_ref }}
+#                   R2_PROJECT_NAME: ${{ vars.R2_PROJECT_NAME }}
+#                   CROWDIN_BRANCH_NAME: ${{ vars.CROWDIN_BRANCH_NAME }}
+#                   REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
+#                   TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
 
-            - name: Retrieve PR information
-              env:
-                  EVENT_NUMBER: ${{ github.event.number }}
-                  EVENT_USERNAME: ${{ github.event.pull_request.user.login }}
-                  HEAD_REF: ${{ github.head_ref }}
-                  DRAFT: ${{ github.event.pull_request.draft }}
-              run: |
-                  mkdir -p .pr
-                  echo "$EVENT_NUMBER" > .pr/NR
-                  echo "$EVENT_USERNAME" > .pr/USERNAME
-                  echo "$HEAD_REF" > .pr/BRANCHNAME
-                  echo "$DRAFT" > .pr/DRAFT
+#             - name: Retrieve PR information
+#               env:
+#                   EVENT_NUMBER: ${{ github.event.number }}
+#                   EVENT_USERNAME: ${{ github.event.pull_request.user.login }}
+#                   HEAD_REF: ${{ github.head_ref }}
+#                   DRAFT: ${{ github.event.pull_request.draft }}
+#               run: |
+#                   mkdir -p .pr
+#                   echo "$EVENT_NUMBER" > .pr/NR
+#                   echo "$EVENT_USERNAME" > .pr/USERNAME
+#                   echo "$HEAD_REF" > .pr/BRANCHNAME
+#                   echo "$DRAFT" > .pr/DRAFT
 
-            - name: Publish to Cloudflare Pages
-              id: publish-to-pages
-              env:
-                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-                  HEAD_BRANCH: ${{ github.head_ref }}
-              run: |
-                  echo "Installing Wrangler CLI"
-                  npm i -g wrangler
-                  echo "Deploying build to Cloudflare Pages"
-                  cd packages/core
-                  directory='dist/'
-                  branch=$(echo "$HEAD_BRANCH" | head -c 20 | sed 's/[\/_\.]/-/g; s/[^a-zA-Z0-9]$/1/')
-                  cf_preview_url=$(wrangler pages deploy $directory --project-name=derivatives-trader --branch=$branch > log.txt 2>&1; echo $?)
-                  echo "------"
-                  preview_url=https://$branch.derivatives-trader.pages.dev
-                  cat log.txt
-                  if grep -q "Deployment complete" log.txt; then
-                    echo "preview_url=$preview_url" >> "$GITHUB_OUTPUT"
-                    echo $preview_url > .pr/PREVIEW_URL
-                  else
-                    echo "Deployment to Cloudflare Pages failed."
-                    exit 1
-                  fi
+#             - name: Publish to Cloudflare Pages
+#               id: publish-to-pages
+#               env:
+#                   CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+#                   CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+#                   HEAD_BRANCH: ${{ github.head_ref }}
+#               run: |
+#                   echo "Installing Wrangler CLI"
+#                   npm i -g wrangler
+#                   echo "Deploying build to Cloudflare Pages"
+#                   cd packages/core
+#                   directory='dist/'
+#                   branch=$(echo "$HEAD_BRANCH" | head -c 20 | sed 's/[\/_\.]/-/g; s/[^a-zA-Z0-9]$/1/')
+#                   cf_preview_url=$(wrangler pages deploy $directory --project-name=derivatives-trader --branch=$branch > log.txt 2>&1; echo $?)
+#                   echo "------"
+#                   preview_url=https://$branch.derivatives-trader.pages.dev
+#                   cat log.txt
+#                   if grep -q "Deployment complete" log.txt; then
+#                     echo "preview_url=$preview_url" >> "$GITHUB_OUTPUT"
+#                     echo $preview_url > .pr/PREVIEW_URL
+#                   else
+#                     echo "Deployment to Cloudflare Pages failed."
+#                     exit 1
+#                   fi
 
-            - name: 'Generate preview link comment'
-              if: success()
-              id: generate_preview_url
-              uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
-              with:
-                  github-token: ${{ github.token }}
-                  script: |
-                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
-                      const preview_url = "${{steps.publish-to-pages.outputs.preview_url}}"
-                      const comment = [
-                          `**Preview Link**: ${preview_url}`,
-                          '| Name | Result |',
-                          '| :--- | :------ |',
-                          `| **Build status**  | Completed ✅ |`,
-                          `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
-                          `| **Action URL**  | [Visit Action](${action_url}) |`,
-                          ''
-                        ].join('\n')
-                      core.setOutput("comment", comment);
+#             - name: 'Generate preview link comment'
+#               if: success()
+#               id: generate_preview_url
+#               uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
+#               with:
+#                   github-token: ${{ github.token }}
+#                   script: |
+#                       const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
+#                       const preview_url = "${{steps.publish-to-pages.outputs.preview_url}}"
+#                       const comment = [
+#                           `**Preview Link**: ${preview_url}`,
+#                           '| Name | Result |',
+#                           '| :--- | :------ |',
+#                           `| **Build status**  | Completed ✅ |`,
+#                           `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
+#                           `| **Action URL**  | [Visit Action](${action_url}) |`,
+#                           ''
+#                         ].join('\n')
+#                       core.setOutput("comment", comment);
 
-            - name: 'Generate failure comment'
-              if: failure()
-              id: generate_failure_comment
-              uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
-              with:
-                  github-token: ${{ github.token }}
-                  script: |
-                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
-                      const comment = [
-                        '| Name | Result |',
-                        '| :--- | :------ |',
-                        `| **Build status**  | Failed ❌ |`,
-                        `| **Action URL**  | [Visit Action](${action_url}) |`,
-                        ''
-                      ].join('\n')
-                      core.setOutput("comment", comment);
+#             - name: 'Generate failure comment'
+#               if: failure()
+#               id: generate_failure_comment
+#               uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736
+#               with:
+#                   github-token: ${{ github.token }}
+#                   script: |
+#                       const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
+#                       const comment = [
+#                         '| Name | Result |',
+#                         '| :--- | :------ |',
+#                         `| **Build status**  | Failed ❌ |`,
+#                         `| **Action URL**  | [Visit Action](${action_url}) |`,
+#                         ''
+#                       ].join('\n')
+#                       core.setOutput("comment", comment);
 
-            - name: Post Cloudflare Pages Preview comment
-              if: success() || failure()
-              uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd
-              with:
-                  header: Cloudflare Pages Preview Comment
-                  number: ${{github.event.number}}
-                  message: ${{steps.generate_preview_url.outputs.comment || steps.generate_failure_comment.outputs.comment }}
-                  recreate: true
+#             - name: Post Cloudflare Pages Preview comment
+#               if: success() || failure()
+#               uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd
+#               with:
+#                   header: Cloudflare Pages Preview Comment
+#                   number: ${{github.event.number}}
+#                   message: ${{steps.generate_preview_url.outputs.comment || steps.generate_failure_comment.outputs.comment }}
+#                   recreate: true
 
-            - name: Upload PR information to artifact
-              uses: actions/upload-artifact@v4
-              with:
-                  name: 'pr-${{github.run_id}}'
-                  path: .pr
+#             - name: Upload PR information to artifact
+#               uses: actions/upload-artifact@v4
+#               with:
+#                   name: 'pr-${{github.run_id}}'
+#                   path: .pr
